can org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.73
neo_version_range=[26.1.2,)
loader_version_range=[4,)

mod_id=keystone_of_oblivion
mod_name=Enigmatic Legacy: Keystone
mod_license=Enigmatic Legacy License, II Edition
mod_version=1.0.2
mod_group_id=net.keystoneofoblivion
mod_authors=Aizistral (original), txmmytwostraps (port)
mod_description=Standalone NeoForge 1.21 port of the Keystone of the Oblivion item from Enigmatic Legacy, by permission of the original author Aizistral.
